default_language_version:
    python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: []
    additional_dependencies: [toml]
    exclude: docs/tutorials

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.4.0
  hooks:
    - id: nbqa-isort

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black-jupyter
