name: python-lint-plus

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches: 
      - "**"

jobs:
  flake8-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run python-lint-plus
        uses: weibullguy/python-lint-plus@v1.9.0
        with:
              python-root-list: "."
              use-black: true
              use-yapf: false
              use-isort: true
              use-docformatter: false
              use-pycodestyle: false
              use-autopep8: false
              use-pydocstyle: true
              use-mypy: false
              use-pylint: true
              use-flake8: true
              use-mccabe: false
              use-radon: false
              use-rstcheck: false
              use-check-manifest: false
              use-pyroma: false
              extra-black-options: "--diff --color"
              extra-yapf-options: ""
              extra-isort-options: "--diff --color "
              extra-docformatter-options: ""
              extra-pycodestyle-options: ""
              extra-pydocstyle-options: ""
              extra-mypy-options: ""
              extra-pylint-options: "--output-format=colorized"
              extra-flake8-options: ""
              extra-mccabe-options: ""
              extra-radon-options: ""
              extra-rstcheck-options: ""
              extra-manifest-options: ""
              extra-pyroma-options: ""